image:
- Visual Studio 2019
configuration:
- Release
- Native
before_build:
# install python 1.5
- 7z x -o"C:\Program Files (x86)\Python" python-1.5.2.zip
# setup Visual C++ build environment
- call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
# upgrade projects
- devenv /Upgrade src/BOD.sln
- devenv /Upgrade Mss32dummy.sln
- devenv /Upgrade tests/UnitTests.sln
- xcopy /Y /E tests\gtest-v1-10 tests\gtest
# set environment variables for additional properties of Visual C++ projects
- set NOSAFESEH=/p:ForceImportBeforeCppTargets=%APPVEYOR_BUILD_FOLDER%\src\nosafeseh.props
build_script:
- msbuild %NOSAFESEH% /p:Configuration=Debug /p:Platform=Win32 Mss32dummy.sln
- msbuild %NOSAFESEH% /p:Platform=Win32 src/BOD.sln
- msbuild %NOSAFESEH% /p:Platform=Win32 tests/UnitTests.sln
- make_setup.bat
test_script:
- tests\%CONFIGURATION%\UnitTests.exe
for:
-
  matrix:
    only:
    - configuration: Native
  build_script:
  - msbuild %NOSAFESEH% /p:Configuration=Debug /p:Platform=Win32 Mss32dummy.sln
  - msbuild %NOSAFESEH% /p:Platform=Win32 src/BOD.sln
  - make_setup.bat
  test_script:
  - echo 'There is no tests for %CONFIGURATION% configuration'
artifacts:
- path: install/*.exe
  name: Blade of Darkness patch installer
- path: install/bin/*.exe
  name: Blade of Darkness main executable
- path: install/bin/**/*.dll
  name: Blade of Darkness library
